In [30]:
import numpy as np
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b = np.zeros((3,4))
c = np.arange(5)
d = np.linspace(0,10,5) #0~10 分五等份
e = np.random.random(4) #4個0~1之間的數(不包含1)
print("a=",a)
print("b=",b)
print("c=",c)
print("d=",d)
print("e=",e)

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
c= [0 1 2 3 4]
d= [  0.    2.5   5.    7.5  10. ]
e= [ 0.20570901  0.77344272  0.16589909  0.58006096]


In [29]:
np.random.random?

In [8]:
# 建立一個 np array
arr = np.array([[1,2,3],[4,5,6]])    #放入list就會轉換喔!
print(arr)
#印出 [[1,2,3],[4,5,6]]的 2*3 矩陣

[[1 2 3]
 [4 5 6]]


In [10]:
# 建立一個 全為 0 的 2*3 矩陣，並指定為 int格式
zero_arr = np.zeros((2,3), dtype=np.int)
print(zero_arr)
#印出 [[0,0,0],[0,0,0]] 的 2*3 矩陣

[[0 0 0]
 [0 0 0]]


In [12]:
# 建立一個長度為12、數值從0~11、格式為 int 的一維陣列
onedim_arr = np.arange(12, dtype=np.int)
print(onedim_arr)
#印出 [0,1,2,3,4,5,6,7,8,9,10,11]

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
# 建立一個最小值1，最大值50，共分五塊相等間距的矩陣
slice_arr = np.linspace(1,50,5)
print(slice_arr)
#印出 [  1.    13.25  25.5   37.75  50.  ] 的 1*5 矩陣
#要轉成 5*1 的矩陣就在後面加上 .reshape((5*1)) 就可以喔！

[  1.    13.25  25.5   37.75  50.  ]


In [20]:
# 建立一個隨機在0~1之間分布的 4*2 矩陣
random_arr = np.random.random( (4, 2) )
print(random_arr)
#印出 [[ 0.92615029  0.12676952], [ 0.33146324  0.51952945],
#[ 0.37010443  0.23092601], [ 0.11052635  0.78243148]]
#值是隨機的，所以你印出來一定跟我不一樣喔！

[[ 0.59990997  0.62318027]
 [ 0.5820409   0.65768171]
 [ 0.54027045  0.24352088]
 [ 0.31675384  0.0467357 ]]
